# Generated by Django 3.1.5 on 2021-03-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='name')),
                ('author_description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(blank=True, max_length=20, null=True, verbose_name='genres')),
                ('genres_description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=50, null=True, verbose_name='publisher')),
                ('publisher_description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50, verbose_name='Series')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pic', models.ImageField(upload_to='uploads/', verbose_name='Picture')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('binding', models.CharField(max_length=20, verbose_name='binding')),
                ('format', models.CharField(max_length=10, verbose_name='format')),
                ('isbn', models.PositiveSmallIntegerField(verbose_name='ISBN')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='pages')),
                ('the_weight', models.PositiveSmallIntegerField(verbose_name='the weight')),
                ('age_restrictions', models.PositiveSmallIntegerField(verbose_name='age restrictions')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='amount ')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='rating')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('year_edition', models.DateField(verbose_name='Year Edition')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Author1', to='book.author', verbose_name='Author')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Genres1', to='book.genres', verbose_name='Genres')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Publisher1', to='book.publisher', verbose_name='Publisher')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Series1', to='book.series', verbose_name='Series')),
            ],
        ),
    ]
