# Generated by Django 3.1.5 on 2021-01-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Author_description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Author_neme',
            field=models.CharField(max_length=50, verbose_name='neme'),
        ),
    ]
