# Generated by Django 3.1.5 on 2021-02-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210226_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(default=1, max_length=20, verbose_name='binding'),
            preserve_default=False,
        ),
    ]
