# Generated by Django 3.1.5 on 2021-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
