# Generated by Django 3.1.5 on 2021-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210131_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_neme', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='Author_neme',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
