# Generated by Django 3.1.5 on 2021-02-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210131_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='Series_neme',
        ),
        migrations.AddField(
            model_name='series',
            name='series',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Series'),
        ),
        migrations.AddField(
            model_name='series',
            name='series_description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Author_description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
