# Generated by Django 3.1.5 on 2021-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(default=1, max_length=100, verbose_name='pages'),
            preserve_default=False,
        ),
    ]
