# Generated by Django 3.1.5 on 2021-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.PositiveSmallIntegerField(default=1, max_length=100, verbose_name='age_restrictions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='the_weight',
            field=models.PositiveSmallIntegerField(default=1, max_length=100, verbose_name='the_weight'),
            preserve_default=False,
        ),
    ]
