# Generated by Django 3.1.5 on 2021-02-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210201_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_neme',
            new_name='Author_name',
        ),
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Series'),
        ),
    ]
