# Generated by Django 3.1.5 on 2021-02-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210201_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='series',
            new_name='series_name',
        ),
    ]
