# Generated by Django 3.1.5 on 2021-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210301_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, max_length=100, verbose_name='age_restrictions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, max_length=10, verbose_name='age_restrictions'),
            preserve_default=False,
        ),
    ]
