# Generated by Django 3.1.5 on 2021-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210301_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(default=1, max_length=20, verbose_name='format'),
            preserve_default=False,
        ),
    ]
