# Generated by Django 3.1.5 on 2021-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210201_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='series_name',
        ),
        migrations.AddField(
            model_name='series',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Series'),
        ),
    ]
