# Generated by Django 3.1.5 on 2021-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveSmallIntegerField(default=1, max_length=13, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.PositiveSmallIntegerField(max_length=3, verbose_name='age restrictions'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.PositiveSmallIntegerField(max_length=10, verbose_name='amount '),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(max_length=10, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(max_length=4, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(max_length=2, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='the_weight',
            field=models.PositiveSmallIntegerField(max_length=5, verbose_name='the weight'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, max_length=20, null=True, verbose_name='Series'),
        ),
    ]
