# Generated by Django 3.1.5 on 2021-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210201_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(blank=True, max_length=20, null=True, verbose_name='genres')),
                ('genres_description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
    ]
