# Generated by Django 3.1.5 on 2021-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=50, null=True, verbose_name='publisher')),
                ('publisher_description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
    ]
