# Generated by Django 3.1.5 on 2021-03-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210301_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Author1', to='book.author', verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.PositiveSmallIntegerField(verbose_name='age restrictions'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='amount '),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveSmallIntegerField(verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='the_weight',
            field=models.PositiveSmallIntegerField(verbose_name='the weight'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Series'),
        ),
    ]
