# Generated by Django 3.1.5 on 2021-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(default='qwert', upload_to='', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
