# Generated by Django 3.1.5 on 2021-03-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210301_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Genres1', to='book.genres', verbose_name='Genres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Publisher1', to='book.publisher', verbose_name='Publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Series1', to='book.series', verbose_name='Series'),
            preserve_default=False,
        ),
    ]
