# Generated by Django 3.1.5 on 2021-03-01 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210301_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 1, 10, 44, 39, 220209, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update'),
        ),
    ]
