# Generated by Django 3.1.5 on 2021-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210224_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='pic',
            field=models.ImageField(default='qw', upload_to='uploads/', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
