# Generated by Django 3.1.5 on 2021-03-01 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210301_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_edition',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 10, 56, 31, 288196, tzinfo=utc), max_length=10, verbose_name='Year Edition'),
            preserve_default=False,
        ),
    ]
