# Generated by Django 3.1.5 on 2021-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_series_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='pic',
        ),
        migrations.AddField(
            model_name='author',
            name='Author_name1',
            field=models.CharField(default='aaa', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
