# Generated by Django 3.1.5 on 2021-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_year_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_edition',
            field=models.DateField(verbose_name='Year Edition'),
        ),
    ]
