# Generated by Django 3.1.5 on 2021-02-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20210224_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Author_name1',
        ),
    ]
