# Generated by Django 3.1.5 on 2021-02-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_author_author_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='pic',
        ),
    ]
