# Generated by Django 3.1.5 on 2021-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_book_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default=1, upload_to='uploads/', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
