# Generated by Django 3.1.5 on 2021-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.CharField(default=1, max_length=50, verbose_name='Series'),
            preserve_default=False,
        ),
    ]
