# Generated by Django 3.1.5 on 2021-02-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20210226_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
    ]
