# Generated by Django 3.1.5 on 2021-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_home_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
