# Generated by Django 3.1.5 on 2021-02-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_remove_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Price',
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(default='default_title', on_delete=django.db.models.deletion.PROTECT, related_name='Author1', to='book.author', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
