# Generated by Django 3.1.5 on 2021-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20210311_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(max_length=50, verbose_name='name'),
        ),
    ]
