# Generated by Django 3.1.5 on 2021-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20210226_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Price',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
