# Generated by Django 3.1.5 on 2021-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default=';', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
