# Generated by Django 3.1.5 on 2021-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='telephone',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='telephone'),
            preserve_default=False,
        ),
    ]
