# Generated by Django 3.1.5 on 2021-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='author_description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
