# Generated by Django 3.1.5 on 2021-03-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='author_description',
            new_name='description',
        ),
    ]
