# Generated by Django 3.1.5 on 2021-03-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210318_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='telephone'),
        ),
    ]
