# Generated by Django 3.1.5 on 2021-03-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210318_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.AddField(
            model_name='orders',
            name='addres',
            field=models.CharField(default='ю', max_length=50, verbose_name='addres'),
            preserve_default=False,
        ),
    ]
