# Generated by Django 3.1.5 on 2021-03-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210318_1005'),
        ('orders', '0013_auto_20210319_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Cart'),
        ),
    ]
