# Generated by Django 3.1.5 on 2021-03-18 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 18, 6, 56, 58, 942163, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookincart',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update'),
        ),
    ]
