# Generated by Django 3.1.5 on 2021-03-18 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210318_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 18, 7, 5, 3, 472112, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update'),
        ),
    ]
